### ISSUE TITLE
Co-forest: w initialization + repeat experiments

### ISSUE THREAD

**Issue by alvarag** [phf1001/semisupervised-learning-in-cibersecurity#115]
I'm sure that you remember the chat that we had about the _w_ initialization on Co-forest classifier, isn't it?

Well, César has been checked the original paper where the co-forest is explained and he has found the same: there is a problem as it is explained and it can't be initialized to 0 (as the pseudocode explains).

We decided to initialize it to a percentage of the instances, but César thinks that it would be a better approximation. We can do a brief meeting to discuss it this week or the next one

The idea is to do something like this:
![imagen](https://user-images.githubusercontent.com/9881614/223781813-a3648be2-536a-4a72-8339-66e95f1f55a4.png)

But instead of using x_u, using x_l (i.e. the labeled instances)

**Comment by phf1001** [comment]
@alvarag Perfect! I will assing time to this issue during the next sprint since I must repeat the experiments if the algorithm changes

**Comment by phf1001** [comment]
- [ ] Comment in code the decisions taken (to initialize w)
- [ ] Aspectos relevantes: bug found

**Comment by alvarag** [comment]
I imagine that the answer is yes, but only for double-checking this: are you fixing the random seed for all the experiments? I mean, we are sure that the subsets of training and testing are the same for all the executions. It's only to ensure that there is nothing there that maybe is confusing us.

**Comment by phf1001** [comment]
@alvarag Yes! I have printed the sets and they are the same. Even more, if the whole "methods" array is completed with the same method, the graphs are exactly the same (for example):

![image](https://user-images.githubusercontent.com/99904180/228563439-25d08936-b4c9-4aa8-8b7a-7a39e32360c7.png)
![image](https://user-images.githubusercontent.com/99904180/228563776-2a0a7d95-6444-43d6-92dd-0be04014a859.png)

I will review the code tomorrow and let you know (I will also quickly re-read the paper), but I have let some experiments running and so far this are the results with more datasets:

* n = 6
![rd5_n6](https://user-images.githubusercontent.com/99904180/228564183-e2952a89-9b9b-4019-984d-20675d5ecf95.png)

* n = 20

![rd_5_n_20](https://user-images.githubusercontent.com/99904180/228564293-2c4d1621-70fd-4c62-b903-087313bd32ba.png)

Have a great evening!

**Comment by alvarag** [comment]
Thanks for double-checking it all. I didn't expected such a huge impact about the W initialization, anyway I have asked to César to this issue.

**Comment by phf1001** [comment]
Okay! Thank you so much. Anyways I will let you know both of you once I have reviewed the code just in case I have made any mistakes (I don't want you to loose time).

**Comment by phf1001** [comment]
@alvarag 

So, after reviewing the code, I am pretty sure that the way we initialize W has an impact on the algorithm since it determines the size of the first subset of U.

Even more, in some cases, it seems that, if there are few trees, it is better to have "bigger W" values (maybe more data is needed). If there are more trees, it could be better to have a smaller subset of U (maybe they can handle the "situation" of having less data by being more on the majority voting, and few "errors" are made because trees are trained with less instances of U (?)).

I have reached this conclusions by watching few graphs so I don't think they are reliable at all, but it is my first thought on the matter.

Nice Thursday!

**Comment by alvarag** [comment]
Yes, I didn't have any doubt about the quality of your code and its accuracy. I was talking this morning with César and we have been thought about even launch a great bunch of experiments to evaluate this behaviour.

It sounds reasonable that the W initialization can have an impact but we are surprised about this impact is higher than we imagined.

So, in summary, we think that we can keep the value as we thought (as César said, an overestimation because we are computing the confidence with instances that have been seen by the estimators. In the meanwhile, if you agree, we can launch an experimentation with 20 or 30 datasets (not only with 2 or 4) and check these issues. Anyway, this can be done in the future, you are focusing now in finishing the web and docuementation (as we told yesterday). In the next meeting we can talk about the experimentation that I have in mind. Are you agree?

Have a nice weekend and good Easter holidays!

**Comment by phf1001** [comment]
@alvarag 

It sounds perfect to me! So, I am going to close the issue and I will not documentate the results until we do the "big experimentation" (since I am already over the time planned for this issue and it will be better to do it "all together").

I will put it on my to-do list though!

P.D. I have created a new label called coforest-w so that we can filter this issues.
