### ISSUE TITLE
docs: diagrams and mockups

### ISSUE THREAD

**Issue by phf1001** [phf1001/semisupervised-learning-in-cibersecurity#94]

**Comment by alvarag** [comment]
Some comments on the documentation, have a nice Sunday!

[anexosAAG.pdf](https://github.com/phf1001/semisupervised-learning-in-cibersecurity/files/10892042/anexosAAG.pdf)
[memoriaAAG.pdf](https://github.com/phf1001/semisupervised-learning-in-cibersecurity/files/10892043/memoriaAAG.pdf)

**Comment by alvarag** [comment]
Comments on the case use diagrams:
- A new user: admin, I think he/she should be able to retrain the model or things like that.
- I like to add a number to the use case, thus the subuse cases can be x.x and it is easier to read the diagram.

**Comment by alvarag** [comment]
Regarding classes diagram:
- I think it would be better to have a more general diagram, something like SSLClassifier inherits from Classifier (i.e. sklearn classifier), and from it inhertis all that you implemented (i.e. Co-Training, Tri-Training...) and these are which have aggregated a sklearn classifier. Maybe tomorrow we can talk about it.


BTW: I like [PlantUML](https://plantuml.com) for designing diagrams, you code them instead of drawing
